steps:
  # Paso 0: Asegura que la carpeta enrichments exista
  - name: ubuntu
    entrypoint: bash
    args:
      - -c
      - |
        mkdir -p enrichments
        touch enrichments/.keep

  # Paso 1: Build de Dockerfile.enrich
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - .
      - '-f'
      - Dockerfile.enrich
    id: Build-Enrich

  # Paso 2: Push al Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
    id: Push-Enrich

  # Paso 3: Deploy como Cloud Run Service
# Versión corregida del Paso 3:
# Paso 3: Deploy como Cloud Run Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - -c
      - |
        if gcloud run services describe ${_SERVICE_NAME} --region=${_DEPLOY_REGION} >/dev/null 2>&1; then
          echo "🔄 Actualizando servicio existente..."
          gcloud run deploy ${_SERVICE_NAME} \
            --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA} \
            --region=${_DEPLOY_REGION} \
            --memory=2Gi \
            --cpu=2 \
            --max-instances=5 \
            --min-instances=1 \
            --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json \
            --update-secrets /secrets/key.json=key-json-secret:latest \
            --args="--enrichments=/enrichments,--iglu-config=/config/resolver.json,--config=/config/config.hocon" \
            --no-allow-unauthenticated
        else
          echo "✨ Creando nuevo servicio..."
          gcloud run deploy ${_SERVICE_NAME} \
            --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA} \
            --region=${_DEPLOY_REGION} \
            --memory=2Gi \
            --cpu=2 \
            --max-instances=5 \
            --min-instances=1 \
            --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json \
            --set-secrets /secrets/key.json=key-json-secret:latest \
            --args="--enrichments=/enrichments,--iglu-config=/config/resolver.json,--config=/config/config.hocon" \
            --no-allow-unauthenticated
        fi


images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_REPOSITORY: enrich
  _AR_PROJECT_ID: baico-platform-dev
  _SERVICE_NAME: enrich-service
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
