steps:
  - name: ubuntu
    args:
      - '-c'
      - |
        mkdir -p enrichments
        touch enrichments/.keep
    entrypoint: bash

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}
      - .
      - '-f'
      - Dockerfile.enrich
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - '-c'
      - |
        gcloud run jobs describe $_SERVICE_NAME --region=$_DEPLOY_REGION >/dev/null 2>&1 \
        && echo "🔄 Updating existing job..." \
        && gcloud run jobs update $_SERVICE_NAME \
          --image ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA} \
          --region $_DEPLOY_REGION \
          --memory 2Gi \
          --cpu 2 \
          --max-retries 5 \
          --set-env-vars "GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json" \
          --add-volume name=credentials,secret=key-json-secret \
          --add-volume-mount volume=credentials,mount-path=/secrets,read-only \
          --args=--enrichments=/enrichments,--iglu-config=/config/resolver.json,--config=/config/config.hocon \
        || gcloud run jobs create $_SERVICE_NAME \
          --image ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA} \
          --region $_DEPLOY_REGION \
          --memory 2Gi \
          --cpu 2 \
          --max-retries 5 \
          --set-env-vars "GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json" \
          --add-volume name=credentials,secret=key-json-secret \
          --add-volume-mount volume=credentials,mount-path=/secrets,read-only \
          --args=--enrichments=/enrichments,--iglu-config=/config/resolver.json,--config=/config/config.hocon
    id: Deploy Job
    entrypoint: bash

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_REPOSITORY: enrich
  _AR_PROJECT_ID: baico-platform-dev
  _SERVICE_NAME: enrich-job
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
