FROM snowplow/snowplow-enrich-pubsub:5.3.0

# Crea las carpetas necesarias dentro de la imagen
RUN mkdir -p  /enrichments


# Copia los archivos si existen
COPY config/config.hocon /config/config.hocon
COPY config/resolver.json /config/resolver.json

# Copia la carpeta vacía (evita error si local/enrichments está vacía)
COPY enrichments /enrichments/
COPY key.json /secrets/key.json

