FROM snowplow/snowplow-enrich-pubsub:5.3.0

# Copia los archivos si existen
COPY config/config.hocon /config/config.hocon
COPY config/resolver.json /config/resolver.json

# Copia la carpeta vacía (evita error si local/enrichments está vacía)
COPY enrichments /enrichments/

COPY wrapper.sh /usr/local/bin/wrapper.sh
RUN chmod +x /usr/local/bin/wrapper.sh

ENTRYPOINT ["/usr/local/bin/wrapper.sh"]