FROM snowplow/snowplow-enrich-pubsub:5.3.0

# Copia configs y enrichments
COPY config/config.hocon   /config/config.hocon
COPY config/resolver.json  /config/resolver.json
COPY enrichments/          /enrichments/

# Copia wrapper.sh — el bit +x ya viene del host
COPY wrapper.sh           /usr/local/bin/wrapper.sh

ENTRYPOINT ["/usr/local/bin/wrapper.sh"]
